# Generated by Django 5.2.15 on 2026-06-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
